1. Create and Inspect an Array
    Create a 1D NumPy array containing integers from 10 to 50 (inclusive) with a step of 5.

    Print its shape, size, and data type.


In [17]:
import numpy as np
a=np.arange(10,51,5)
print(a)
print("type= ",type(a))
print("shape= ",a.shape)
print("size= ",a.size)
print(a.dtype)

[10 15 20 25 30 35 40 45 50]
type=  <class 'numpy.ndarray'>
shape=  (9,)
size=  9
int64


2. Generate a Matrix with Random Values
    Generate a 4x5 NumPy array with random integers between 1 and 100.

    Find the maximum and minimum values, along with their indices.

In [15]:
a=np.random.random((3,3))
print(a)
b=np.random.randint(1,100,(4,5))
print(b)
print("max =",np.max(b),"min= ",np.min(b))
print("index of b= ",b.shape)

[[0.86387343 0.5247752  0.8211486 ]
 [0.66335544 0.58948423 0.18126412]
 [0.39262096 0.37549755 0.43071987]]
[[54 31 89 84 12]
 [44 90 40  2 92]
 [97 53 15 52 94]
 [49 73 54 40  5]]
max = 97 min=  2
index of b=  (4, 5)


3. Reshape an Array
    Create a 1D array of numbers from 1 to 24, then reshape it into a 4x6 matrix.

    Extract the 2nd row and 3rd column.

In [36]:
a=np.arange(1,25)
b=np.array((4,6))
b=a.reshape(4,6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


4. Boolean Indexing
    Given a NumPy array of 15 random integers between 0 and 50, find all elements greater than 25 and replace them with -1.

In [39]:
a=np.random.randint(0,50,size=15)
print(a)
a[a>25]=-1 #or bool_idx= (a>25) #a[bool_idx]=-1
print(a)

[ 5 31 24 16  6  5 15 12  5 37 44 31  6  0  6]
[ 5 -1 24 16  6  5 15 12  5 -1 -1 -1  6  0  6]


5. Mathematical Operations
    Create two 1D NumPy arrays:
    a = [1, 2, 3, 4, 5] and b = [10, 20, 30, 40, 50]

    Perform element-wise addition, subtraction, multiplication, and division.

In [44]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


6. Statistical Computations
    Generate a 5x5 matrix with random floats between 0 and 1.

    Compute the mean, median, variance, and standard deviation.

In [47]:
a=np.random.random((5,5))
print(a)
print("mean = ",np.mean(a))
print("median = ",np.median(a))
print("standard deviation = ",np.std(a))
print("variance = ",np.var(a))

[[0.42331805 0.23659916 0.10805371 0.19739943 0.16129542]
 [0.83252892 0.76724412 0.32692512 0.62037699 0.178064  ]
 [0.13247903 0.27281976 0.19781488 0.57770985 0.47320662]
 [0.48409818 0.42797345 0.96217057 0.73156146 0.75205586]
 [0.70729615 0.26574858 0.86468769 0.47731881 0.39705775]]
mean =  0.4630321429621195
median =  0.42797345164094647
standard deviation =  0.25250678597404946
variance =  0.06375967696294443


7. Matrix Multiplication
    Create two matrices:

    A is 3x2 with values from 1 to 6.

    B is 2x3 with values from 7 to 12.
    Perform matrix multiplication (A @ B) and display the result.

In [57]:
a=np.arange(1,7)
a=a.reshape(3,2)
b=np.arange(7,13)
b=b.reshape(2,3)
print(a)
print(b)
print(a@b)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


8. Slice and Modify
    Create a 6x6 array of integers from 1 to 36.

    Extract the 3x3 sub-matrix from the center and set all its values to 0.

In [61]:
a=np.arange(1,37)
a=a.reshape(6,6)
b=a[2:5,2:5]
print(b)
b[:,:]=0
print(a)

[[15 16 17]
 [21 22 23]
 [27 28 29]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14  0  0  0 18]
 [19 20  0  0  0 24]
 [25 26  0  0  0 30]
 [31 32 33 34 35 36]]


9. Use of np.where
    Create a NumPy array with values [5, 10, 15, 20, 25].

    Replace all elements greater than 15 with 99, otherwise replace with 0.

In [64]:
a=np.array([5,10,15,20,25])
bool_idx=(a>15)
a[bool_idx]=99
a[a<=15]=0
print(a)

[ 0  0  0 99 99]



10. Broadcasting Example
    Create a 4x4 array filled with 10s.

    Subtract a 1D array [0, 1, 2, 3] from each row using NumPy broadcasting.

In [67]:
a=np.full((4,4),10) #shape 4,4
print(a)
b=np.array([0,1,2,3]) #shape 1,4
c=a-b
print(c)
#or we could do
bb= np.tile(b,(4,1))
print(a-b)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
[[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
